import os

# Default values
DEFAULT_ACCOUNT = "051556718043"
DEFAULT_REGION = "us-east-1"

CDK_DEFAULT_ACCOUNT = os.environ.get("CDK_DEFAULT_ACCOUNT", DEFAULT_ACCOUNT)
CDK_DEFAULT_REGION = os.environ.get("CDK_DEFAULT_REGION", DEFAULT_REGION)
